Add px optimize command
ampproject/px-toolbox-php pull request #8
Opened 2022-01-10 15:09 UTC by ediamin

This PR adds a new command `px optimize`. It takes a filepath or a string of HTML via STDIN to optimize, and outputs the optimized result to STDOUT.

Usage,
```
px optimize path/to/file.html
// or
echo '<amp-img src="image.jpg" width="500" height="500">' | px optimize
```

Closes #3

2022-01-12 15:22 UTC, ediamin commented
@schlessera I've update the code using the `PageExperience\Engine`. Though I'm not sure about using the `ConfiguredStubbedRemoteGetRequest::create()` as the first param of the Engine, I'm following the code in Analyze command. Should I remove the param or keep as it is for now?

2022-01-18 16:14 UTC, schlessera commented
@ediamin It's fine for now to use the `ConfiguredStubbedRemoteGetRequest::create()` helper for now. This is meant to produce a cached offline response to make development and testing faster.

Later on we will switch to a live, but cached implementation. But for now, this is good enough.

2022-01-24 12:41 UTC, ediamin commented
@schlessera I've update the code and added tests. To resolve the GH fail checks I've created another PR https://github.com/ampproject/px-toolbox-php/pull/13.

2022-02-01 19:11 UTC, schlessera requested changes

2022-02-01 19:11 UTC, schlessera commented on src/Cli/Command/Optimize.php
> + * Commands that deal with the AMP optimizer.
```suggestion
 * Commands that deal with the PX Engine Optimizer.
```

2022-02-01 19:11 UTC, schlessera commented on src/Cli/Command/Optimize.php
> +    const HELP_TEXT = 'Run a file or HTML through the AMP Optimizer.';
```suggestion
    const HELP_TEXT = 'Run a file or a string of HTML through the PX Engine Optimizer.';
```

2022-02-01 19:11 UTC, schlessera commented on src/Cli/Command/Optimize.php
> +            "Input file to run through the AMP Optimizer. Omit or use '-' to read from STDIN.",
```suggestion
            "Input file to run through the PX Engine Optimizer. Omit or use '-' to read from STDIN.",
```

2022-02-01 19:11 UTC, schlessera commented on src/Cli/Command/Optimize.php
> +        // TODO: Display errors collected by the ErrorCollection in AmpOptimizer::optimizeHtml.
This doesn't exist for the PXE Optimizer (yet).
```suggestion
```

2022-02-01 19:11 UTC, schlessera commented on tests/src/Cli/OptimizeTest.php
> +use AmpProject\Exception\Cli\InvalidArgument;
Imports should always be sorted.
```suggestion
use AmpProject\Cli\Command;
use AmpProject\Cli\Executable;
use AmpProject\Cli\Options;
use AmpProject\Exception\Cli\InvalidArgument;
use org\bovigo\vfs\vfsStream;
use PageExperience\Cli\Command\Optimize;
use PageExperience\Tests\TestCase;
```

2022-02-01 19:11 UTC, schlessera commented on tests/src/Cli/OptimizeTest.php
> + * @package ampproject/px-toolbox-php
```suggestion
 * @package ampproject/px-toolbox
```

2022-02-03 23:40 UTC, schlessera approved these changes

2022-02-03 23:40 UTC, merged